# coding: utf-8

"""
    OpenAPI3Definition 62

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.artist import Artist

class TestArtist(unittest.TestCase):
    """Artist unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Artist:
        """Test Artist
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Artist`
        """
        model = Artist()
        if include_optional:
            return Artist(
                id = 56,
                name = '',
                link = '',
                picture = '',
                picture_small = '',
                picture_medium = '',
                picture_big = '',
                picture_xl = '',
                tracklist = '',
                type = '',
                artist = openapi_client.models.artist.Artist(
                    id = 56, 
                    name = '', 
                    link = '', 
                    picture = '', 
                    picture_small = '', 
                    picture_medium = '', 
                    picture_big = '', 
                    picture_xl = '', 
                    tracklist = '', 
                    type = '', )
            )
        else:
            return Artist(
        )
        """

    def testArtist(self):
        """Test Artist"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
