# coding: utf-8

"""
    OpenAPI3Definition 62

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_get_album(self) -> None:
        """Test case for get_album

        """
        pass

    def test_get_artist(self) -> None:
        """Test case for get_artist

        """
        pass

    def test_get_artist_albums(self) -> None:
        """Test case for get_artist_albums

        """
        pass

    def test_get_artist_radio(self) -> None:
        """Test case for get_artist_radio

        """
        pass

    def test_get_artist_top_tracks(self) -> None:
        """Test case for get_artist_top_tracks

        """
        pass

    def test_get_playlist(self) -> None:
        """Test case for get_playlist

        """
        pass

    def test_get_playlist_tracks(self) -> None:
        """Test case for get_playlist_tracks

        """
        pass

    def test_get_related_artists(self) -> None:
        """Test case for get_related_artists

        """
        pass


if __name__ == '__main__':
    unittest.main()
