# coding: utf-8

"""
    OpenAPI3Definition 62

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.creator import Creator
from openapi_client.models.playlist_tracks import PlaylistTracks
from typing import Optional, Set
from typing_extensions import Self

class Playlist(BaseModel):
    """
    Playlist
    """ # noqa: E501
    id: Optional[StrictInt] = None
    title: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    duration: Optional[StrictInt] = None
    public: Optional[StrictBool] = None
    is_loved_track: Optional[StrictBool] = None
    collaborative: Optional[StrictBool] = None
    nb_tracks: Optional[StrictInt] = None
    fans: Optional[StrictInt] = None
    link: Optional[StrictStr] = None
    share: Optional[StrictStr] = None
    picture: Optional[StrictStr] = None
    picture_small: Optional[StrictStr] = None
    picture_medium: Optional[StrictStr] = None
    picture_big: Optional[StrictStr] = None
    picture_xl: Optional[StrictStr] = None
    checksum: Optional[StrictStr] = None
    tracklist: Optional[StrictStr] = None
    creation_date: Optional[StrictStr] = None
    creator: Optional[Creator] = None
    type: Optional[StrictStr] = None
    tracks: Optional[PlaylistTracks] = None
    __properties: ClassVar[List[str]] = ["id", "title", "description", "duration", "public", "is_loved_track", "collaborative", "nb_tracks", "fans", "link", "share", "picture", "picture_small", "picture_medium", "picture_big", "picture_xl", "checksum", "tracklist", "creation_date", "creator", "type", "tracks"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Playlist from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of creator
        if self.creator:
            _dict['creator'] = self.creator.to_dict()
        # override the default output from pydantic by calling `to_dict()` of tracks
        if self.tracks:
            _dict['tracks'] = self.tracks.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Playlist from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "title": obj.get("title"),
            "description": obj.get("description"),
            "duration": obj.get("duration"),
            "public": obj.get("public"),
            "is_loved_track": obj.get("is_loved_track"),
            "collaborative": obj.get("collaborative"),
            "nb_tracks": obj.get("nb_tracks"),
            "fans": obj.get("fans"),
            "link": obj.get("link"),
            "share": obj.get("share"),
            "picture": obj.get("picture"),
            "picture_small": obj.get("picture_small"),
            "picture_medium": obj.get("picture_medium"),
            "picture_big": obj.get("picture_big"),
            "picture_xl": obj.get("picture_xl"),
            "checksum": obj.get("checksum"),
            "tracklist": obj.get("tracklist"),
            "creation_date": obj.get("creation_date"),
            "creator": Creator.from_dict(obj["creator"]) if obj.get("creator") is not None else None,
            "type": obj.get("type"),
            "tracks": PlaylistTracks.from_dict(obj["tracks"]) if obj.get("tracks") is not None else None
        })
        return _obj


